version: '3'
services:
  mongodb:
    build:
      context: ./mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpass
    volumes:
      - C:\Users\hp\Desktop\bojanagolubovic-makeup\mongo-data:/data/db:rw
    ports:
      - "27017:27017"

volumes:
  mongo-data: